apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyconverterservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyconverterservice
  template:
    metadata:
      labels:
        app: currencyconverterservice
    spec:
      containers:
      - name: myapp
        image: stefanpapp/currencyconverterservice
        command: ["python", "-m", "currency_converter_service"]
        stdin: true
        tty: true
        # imagePullPolicy: Never
        ports:
        - containerPort: 8082
