apiVersion: v1
kind: Service
metadata:
  name: currencyconverterservice
  namespace: default
  labels:
      app: currencyconverterservice
spec:
  type: NodePort
  selector:
    app: currencyconverterservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8082
      nodePort: 30002
